### ISSUE TITLE
libc

### ISSUE THREAD

**Issue by AlixAbbasi** [m0r3n/frop#1]
Why not adding the functionality to search in Libc?
To me it is weird that you are only looking at the ELF files. I can extend it but I think it is much faster for you to do it.

**Comment by fervagar** [comment]
Yes, actually I started to implement a search functionality but for time reasons I ended aborting it. The reason of the ELF files is the same, as commented in the "readme" file this was a final project of my computer science degree so I was very limited by both time and scope... Nowadays I don't have time to continue the project but maybe in a future I will implement more functionalities. Thanks for the recommendations, I really appreciate it :+1: 

If you want to implement it you are welcome, of course you would be named as contributor ;). Here is the documentation, although it is written in Spanish.... http://cybersecurity.upv.es/downloads/frop.pdf
